version: 0.0.1-SNAPSHOT.{build}
os: Windows Server 2012
services: iis
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://apache.crihan.fr/dist/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.1\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - mvn clean package -DskipTest
test_script:
  - mvn clean install
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
